#!/bin/bash
#
# dotfile 1.0 
#
# Copyright (C) 2019 Angel. uGeek
# ugeekpodcast@gmail.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
#



if [ $1 = "-h" ]
then
echo "
Modo de empleo: dotfile [nombre_del_archivo] [categoría]

ejem:  dotfile init.el emacs

Enviará el archivo init.el a la carpeta emacs dentro de la carpeta ~/dotfile.
Además, creará un archivo init.el.sh, para reconstruir el archivo.



dotfile -c <NOMBRE DEL PC>
dotfile -b [RUTA DEL ARCHIVO dotfile.org] 
dotfile -b $PWD -> backup en orgmode

Backup de cron:

dotfile -c <NOMBRE DEL PC>

Nos guardará en la carpeta con el nombre del pc, el archivo con su fecha.

Para restaurar un cron:

ejem: crontab [ARCHIVO RESTAURACIÓN CRON]

"

else  
if [ $1 = "-c" ]
then
mkdir -p ~/dotfile/cron/$2
crontab -l > ~/dotfile/cron/$2/cron_$(date +"%Y-%m-%d_%T")
echo " Creada la copia de seguridad de cron con éxito"
else


if [ $1 = "-b" ]
then
rm ~/dotfile/dotfile.org
find $HOME/dotfile/ -type f -not -name dotfile.org  -exec echo "* {}" \; -exec cat {} \; > $2/dotfile.org
cp ~/dotfile/dotfile.org ~/dotfile/dotfile/$(date +"%Y-%m-%d_%T")_dotfile.org
else


# Inicia dotfile
mkdir -p ~/dotfile/$2
cp -r $1 ~/dotfile/$2/

clear

echo "$1 <---Enviado a--> $2" 
echo "cp $1 $(pwd | sed "s,^$HOME,~,")" > ~/dotfile/$2/$1.sh
echo "$2,$1,$(pwd | sed "s,^$HOME,~,")",$(date +"%Y-%m-%d_%T"),$(hostname) >> ~/dotfile/dotfile/log
fi
fi
fi
